const COLORS=['#ef476f','#118ab2','#06d6a0','#8338ec','#ff9f1c','#8ac926','#ff595e','#1982c4'];
const names=['Coral','Ocean','Mint','Violet','Tangerine','Lime','Rose','Sky'];
const starts=[{x:10,y:10},{x:90,y:10},{x:10,y:50},{x:90,y:50},{x:10,y:94},{x:50,y:94},{x:90,y:94},{x:50,y:5}];
const obstacles=[{x:22,y:12},{x:29,y:16},{x:75,y:24},{x:84,y:20},{x:35,y:31},{x:58,y:28},{x:66,y:25},{x:15,y:41},{x:22,y:44},{x:81,y:40},{x:52,y:54},{x:29,y:58},{x:68,y:64},{x:36,y:76},{x:55,y:73},{x:79,y:78},{x:84,y:90},{x:72,y:83},{x:39,y:66},{x:89,y:60}];
let players=[],current=0,rolled=false,validMoves=[],result='';
const $=id=>document.getElementById(id); const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y); const step=5.1;
function setup(){const n=+$('playerCount').value;players=Array.from({length:n},(_,i)=>({id:i,name:names[i],color:COLORS[i],x:starts[i].x,y:starts[i].y,alive:true}));current=0;rolled=false;validMoves=[];$('setup').hidden=true;$('game').hidden=false;render();message('Spin to begin.');}
function render(){const t=$('tokens');t.innerHTML='';players.forEach(p=>{const e=document.createElement('div');e.className='token '+(p.id===current?'current ':'')+(!p.alive?'out':'');e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.background=p.color;t.appendChild(e)});$('turnText').textContent=players[current]?.alive?`${players[current].name}'s turn`:'Game over';$('players').innerHTML=players.map(p=>`<div class="player-row"><i class="dot" style="background:${p.color}"></i>${p.name} ${p.alive?'':'(tagged out)'}</div>`).join('');drawMoves();}
function message(s){$('message').textContent=s}
function occupied(x,y,except){return players.some(p=>p.alive&&p.id!==except&&dist(p,{x,y})<3.5)}
function legalMoves(p,kind){const moves=[];for(const dx of [-1,0,1])for(const dy of [-1,0,1]){if(!dx&&!dy)continue;const x=p.x+dx*step,y=p.y+dy*step;if(x<5||x>95||y<5||y>95)continue;if(obstacles.some(o=>dist(o,{x,y})<4.5))continue;if(occupied(x,y,p.id))continue;const light=(Math.round(x/5)%2===0);if(kind==='white'&&!light||kind==='blue'&&light||kind==='anything'||kind==='light')moves.push({x,y});}return moves}
function drawMoves(){document.querySelectorAll('.move-choice').forEach(e=>e.remove());if(!rolled||!validMoves.length)return;validMoves.forEach(m=>{const e=document.createElement('button');e.className='move-choice';e.style.left=m.x+'%';e.style.top=m.y+'%';e.title='Move here';e.onclick=()=>moveTo(m);$('board').appendChild(e)})}
function spin(){if(rolled||!players[current]?.alive)return;rolled=true;const results=['white','blue','anything','skip'];result=results[Math.floor(Math.random()*results.length)];$('spinner').textContent=result==='anything'?'ANY':result.toUpperCase();const p=players[current];if(result==='skip'){message(`${p.name} skipped.`);return nextTurn()}validMoves=legalMoves(p,result);if(!validMoves.length){message(`${p.name} has no legal move and is tagged out.`);p.alive=false;return nextTurn()}message(`${p.name}: click a highlighted adjacent hexagon on the board to move.`);render()}
function moveTo(target){if(!rolled||!validMoves.some(m=>m.x===target.x&&m.y===target.y))return;const p=players[current];const victim=players.find(q=>q.alive&&q.id!==p.id&&dist(q,target)<3.5);p.x=target.x;p.y=target.y;if(victim){victim.alive=false;message(`${p.name} tagged ${victim.name}!`)}else message(`${p.name} moved.`);validMoves=[];render();setTimeout(nextTurn,500)}
function nextTurn(){const alive=players.filter(p=>p.alive);if(alive.length<=1){render();message(`${alive[0]?.name||'Nobody'} wins!`);$('roll').disabled=true;return}let i=current;do{i=(i+1)%players.length}while(!players[i].alive);current=i;rolled=false;validMoves=[];render();$('roll').disabled=false)}
$('startGame').onclick=setup;$('newGame').onclick=()=>location.reload();$('roll').onclick=spin;